/**
 * This file lives outside of the `src/wordpress` directory on
 * purpose.
 *
 * `src/wordpress` hosts autogenerated code and is added to eslint
 * and NX ignore lists. However, this test file is written by hand
 * and should still be linted and picked up by the test runner.
 */

import { getWordPressModuleDetails } from '../wordpress/get-wordpress-module-details';

describe('getWordPressModuleDetails()', () => {
	it('should return a data loader module', async () => {
		const module = getWordPressModuleDetails();
		// The core bundle ships as a solid tar.zst (see
		// docs/streaming-tar-zst-core-bundle.md).
		expect(module.url).toMatch(/\/wp-\d\.\d\.tar\.zst$/);
		expect(module.format).toBe('tar.zst');
		expect(module.container).toBe('tar');
		expect(module.codec).toBe('zstd');
		expect(typeof module.sha256).toBe('string');
		expect(module.fileCount).toBeGreaterThan(0);
	});
});
