// @ts-ignore
import url_beta from './wp-beta.tar.zst?url';
// @ts-ignore
import url_7_0 from './wp-7.0.tar.zst?url';
// @ts-ignore
import url_6_9 from './wp-6.9.tar.zst?url';
// @ts-ignore
import url_6_8 from './wp-6.8.tar.zst?url';
// @ts-ignore
import url_6_7 from './wp-6.7.tar.zst?url';
// @ts-ignore
import url_6_6 from './wp-6.6.tar.zst?url';
// @ts-ignore
import url_6_5 from './wp-6.5.tar.zst?url';
// @ts-ignore
import url_6_4 from './wp-6.4.tar.zst?url';
// @ts-ignore
import url_6_3 from './wp-6.3.tar.zst?url';

/**
 * This file was auto generated by packages/playground/wordpress-builds/build/build.js
 * and packages/playground/wordpress-builds/build/build-tar-zst.mjs
 * DO NOT CHANGE MANUALLY!
 * This file must statically exists in the project because of the way
 * vite resolves imports.
 */
export interface WordPressModuleDetails {
	/** Bundle container/codec. 'tar.zst' = solid zstd tar (streaming extract); 'zip' = per-entry DEFLATE. */
	format: 'tar.zst' | 'zip';
	/** Archive container, present for tar.zst bundles. */
	container?: 'tar';
	/** Compression codec, present for tar.zst bundles. */
	codec?: 'zstd';
	/** Compressed byte length of the bundle. */
	size: number;
	/** URL (or dev filesystem path) of the bundle. */
	url: string;
	/** SHA-256 of the compressed bundle, present for local tar.zst bundles. */
	sha256?: string;
	/** Number of regular files in the bundle, used for streaming-extract parity. */
	fileCount?: number;
}

export function getWordPressModuleDetails(
	wpVersion: string = "7.0"
): WordPressModuleDetails {
	switch (wpVersion) {
		
		case 'trunk':
			return {
				format: 'zip',
				size: 0,
				url: "https://github.com/WordPress/WordPress/archive/refs/heads/master.zip",
			};
			
		case 'beta':
			/** @ts-ignore */
			return {
				format: 'tar.zst',
				container: 'tar',
				codec: 'zstd',
				size: 23684339,
				sha256: "3359a7a48001299bdd7c9bf7a470001d808720c115c8d618d1f3eaa31bc8c00f",
				fileCount: 1817,
				url: url_beta,
			};
			
		case '7.0':
			/** @ts-ignore */
			return {
				format: 'tar.zst',
				container: 'tar',
				codec: 'zstd',
				size: 23675647,
				sha256: "d310fe2e67710c2b0a204a7631cac05ba2b8ac345edfdfa78d33fbdf56844687",
				fileCount: 1816,
				url: url_7_0,
			};
			
		case '6.9':
			/** @ts-ignore */
			return {
				format: 'tar.zst',
				container: 'tar',
				codec: 'zstd',
				size: 20836400,
				sha256: "0e8de117ce88dc92db872ed512ffcf60165089ad5043e4a7c529b45f3f9e47f3",
				fileCount: 1595,
				url: url_6_9,
			};
			
		case '6.8':
			/** @ts-ignore */
			return {
				format: 'tar.zst',
				container: 'tar',
				codec: 'zstd',
				size: 20843941,
				sha256: "b202710bf794fe61e243af9f2e3fc1a873c72ec4049997dedd3e9076c860f5b7",
				fileCount: 1535,
				url: url_6_8,
			};
			
		case '6.7':
			/** @ts-ignore */
			return {
				format: 'tar.zst',
				container: 'tar',
				codec: 'zstd',
				size: 20718481,
				sha256: "34a31c4109f916d3e0d32a129475ea377976b50caa7dbcade5dd3dad3b89eebb",
				fileCount: 1529,
				url: url_6_7,
			};
			
		case '6.6':
			/** @ts-ignore */
			return {
				format: 'tar.zst',
				container: 'tar',
				codec: 'zstd',
				size: 15519597,
				sha256: "c6f5ad007caeb7bb765d86589ed5dcd1adca5644d1e4c260f60f6b6f4ee89cff",
				fileCount: 1368,
				url: url_6_6,
			};
			
		case '6.5':
			/** @ts-ignore */
			return {
				format: 'tar.zst',
				container: 'tar',
				codec: 'zstd',
				size: 15604856,
				sha256: "59dba952c6054307166c773e77d2300140204a04978f0d8d307a8fdefe2ade28",
				fileCount: 1360,
				url: url_6_5,
			};
			
		case '6.4':
			/** @ts-ignore */
			return {
				format: 'tar.zst',
				container: 'tar',
				codec: 'zstd',
				size: 15451315,
				sha256: "aa54b2874779c7990092d3d0510df44e11418bbf291c418ea16f23791bb810d5",
				fileCount: 1332,
				url: url_6_4,
			};
			
		case '6.3':
			/** @ts-ignore */
			return {
				format: 'tar.zst',
				container: 'tar',
				codec: 'zstd',
				size: 2170768,
				sha256: "fe65cef400db9076c4ba601c70e271d547d3c86229a6a8b6dc5fd527b35d54c2",
				fileCount: 1253,
				url: url_6_3,
			};
			
		case 'nightly':
			return {
				format: 'zip',
				size: 0,
				url: "https://github.com/WordPress/WordPress/archive/refs/heads/master.zip",
			};
		
	}
	throw new Error('Unsupported WordPress module: ' + wpVersion);
}
