// @ts-ignore
import url_beta from './wp-beta.tar.zst?url';
// @ts-ignore
import url_7_0 from './wp-7.0.tar.zst?url';
// @ts-ignore
import url_6_9 from './wp-6.9.tar.zst?url';
// @ts-ignore
import url_6_8 from './wp-6.8.tar.zst?url';
// @ts-ignore
import url_6_7 from './wp-6.7.tar.zst?url';
// @ts-ignore
import url_6_6 from './wp-6.6.tar.zst?url';
// @ts-ignore
import url_6_5 from './wp-6.5.tar.zst?url';
// @ts-ignore
import url_6_4 from './wp-6.4.tar.zst?url';
// @ts-ignore
import url_6_3 from './wp-6.3.tar.zst?url';

/**
 * This file was auto generated by packages/playground/wordpress-builds/build/build.js
 * and packages/playground/wordpress-builds/build/build-tar-zst.mjs
 * DO NOT CHANGE MANUALLY!
 * This file must statically exists in the project because of the way
 * vite resolves imports.
 */
export interface WordPressModuleDetails {
	/** Bundle container/codec. 'tar.zst' = solid zstd tar (streaming extract); 'zip' = per-entry DEFLATE. */
	format: 'tar.zst' | 'zip';
	/** Archive container. */
	container: 'tar' | 'zip';
	/** Compression codec used by the archive payload. */
	codec: 'zstd' | 'deflate';
	/** Compressed byte length of the bundle. */
	size: number;
	/** URL (or dev filesystem path) of the bundle. */
	url: string;
	/** SHA-256 of the compressed bundle, present for local tar.zst bundles. */
	sha256?: string;
	/** Number of regular files in the bundle, used for streaming-extract parity. */
	fileCount?: number;
}

export function getWordPressModuleDetails(
	wpVersion: string = "7.0"
): WordPressModuleDetails {
	switch (wpVersion) {
		
		case 'trunk':
			return {
				format: 'zip',
				container: 'zip',
				codec: 'deflate',
				size: 0,
				url: "https://github.com/WordPress/WordPress/archive/refs/heads/master.zip",
			};
			
		case 'beta':
			/** @ts-ignore */
			return {
				format: 'tar.zst',
				container: 'tar',
				codec: 'zstd',
				size: 4688560,
				sha256: "7f9ea61f1cacfc20b6e97a24c752440319960395257e9b7aad0ea210add5c7ac",
				fileCount: 1816,
				url: url_beta,
			};
			
		case '7.0':
			/** @ts-ignore */
			return {
				format: 'tar.zst',
				container: 'tar',
				codec: 'zstd',
				size: 4686587,
				sha256: "c7c844c36814bd408da4fb67870eebbbce8982db162fd97b279be47e24f6a35a",
				fileCount: 1815,
				url: url_7_0,
			};
			
		case '6.9':
			/** @ts-ignore */
			return {
				format: 'tar.zst',
				container: 'tar',
				codec: 'zstd',
				size: 4288685,
				sha256: "aa5d2a84db7c2b171934a75f24cd7e68b5d78731dfdf704bc6670987e72563fe",
				fileCount: 1594,
				url: url_6_9,
			};
			
		case '6.8':
			/** @ts-ignore */
			return {
				format: 'tar.zst',
				container: 'tar',
				codec: 'zstd',
				size: 4327490,
				sha256: "e07cd5732533c6d6ca66e7215da9de89990ff66011928b2ea25334b2fc9ebd2b",
				fileCount: 1534,
				url: url_6_8,
			};
			
		case '6.7':
			/** @ts-ignore */
			return {
				format: 'tar.zst',
				container: 'tar',
				codec: 'zstd',
				size: 4298045,
				sha256: "fcd44d9f9e4b842cf30a8699992c64a4ddbba5e3dceaab42a8a384deef32e8b4",
				fileCount: 1528,
				url: url_6_7,
			};
			
		case '6.6':
			/** @ts-ignore */
			return {
				format: 'tar.zst',
				container: 'tar',
				codec: 'zstd',
				size: 3438280,
				sha256: "97e0c3ee8e542b4085387f4552cb8fdc184c703ff27472843c1a987f4c6b67b5",
				fileCount: 1367,
				url: url_6_6,
			};
			
		case '6.5':
			/** @ts-ignore */
			return {
				format: 'tar.zst',
				container: 'tar',
				codec: 'zstd',
				size: 3382945,
				sha256: "baf97b3af1e2d7e80abaa6633a6794df297daa859531fe1f1b690f257b682079",
				fileCount: 1359,
				url: url_6_5,
			};
			
		case '6.4':
			/** @ts-ignore */
			return {
				format: 'tar.zst',
				container: 'tar',
				codec: 'zstd',
				size: 3300853,
				sha256: "71b7fc7cbba322de2fae7642c81db7f1c682d08c4afefba2c091110e95cb39be",
				fileCount: 1331,
				url: url_6_4,
			};
			
		case '6.3':
			/** @ts-ignore */
			return {
				format: 'tar.zst',
				container: 'tar',
				codec: 'zstd',
				size: 2170768,
				sha256: "fe65cef400db9076c4ba601c70e271d547d3c86229a6a8b6dc5fd527b35d54c2",
				fileCount: 1253,
				url: url_6_3,
			};
			
		case 'nightly':
			return {
				format: 'zip',
				container: 'zip',
				codec: 'deflate',
				size: 0,
				url: "https://github.com/WordPress/WordPress/archive/refs/heads/master.zip",
			};
		
	}
	throw new Error('Unsupported WordPress module: ' + wpVersion);
}
